language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install:
- npm install express mocha supertest chai
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: e3ad0881-5717-41f5-be4b-e903cc203198
  app: continuosintegration
  on:
    repo: ciisw/SwIC
addons:
  sonarcloud: true
script:
  - npm run test
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=nicoromero3210-github -Dsonar.projectKey=NicoRomero3210_cii_SwIC -Dsonar.sources='./src' -X
 
